package fr.dutra.tools.maven.deptree.model;

import java.io.BufferedWriter;
import java.io.IOException;

import org.apache.commons.io.output.StringBuilderWriter;


/**
 * Generates an output that is identical to the output generated by the following maven command:
 * <pre>mvn dependency:tree -DoutputType=text -Dtokens=standard</pre>
 * @author Alexandre Dutra
 *
 */
public class MavenDependencyNodeToStringVisitor implements MavenDependencyNodeVisitor {

    private final StringBuilderWriter sbw;

    private final BufferedWriter bw;

    public MavenDependencyNodeToStringVisitor() {
        sbw = new StringBuilderWriter();
        bw = new BufferedWriter(sbw);
    }

    public void visit(MavenDependencyNode node){
        try {
            writeNode(node);
            for (MavenDependencyNode child : node.getChildNodes()) {
                visit(child);
            }
        } catch (IOException e) {
        }
    }

    private void writeNode(MavenDependencyNode node) throws IOException {
        //the tree symbols
        writeTreeSymbols(node);
        //the node itself
        bw.write(node.toArtifactCanonicalForm());
        bw.newLine();
    }

    private void writeTreeSymbols(MavenDependencyNode node) throws IOException {
        if(node.getParent() != null) {
            writeParentTreeSymbols(node.getParent());
            if(node == node.getParent().getLastChildNode()) {
                bw.write("\\- ");
            } else {
                bw.write("+- ");
            }
        }
    }

    private void writeParentTreeSymbols(MavenDependencyNode node) throws IOException {
        if(node.getParent() != null) {
            writeParentTreeSymbols(node.getParent());
            if(node == node.getParent().getLastChildNode()) {
                bw.write("   ");
            } else {
                bw.write("|  ");
            }
        }
    }

    @Override
    public String toString() {
        try {
            bw.flush();
            sbw.flush();
            return sbw.toString();
        } catch (IOException e) {
            return null;
        } finally {
            try {
                bw.close();
            } catch (IOException e) {
            }
            sbw.close();
        }
    }


}
