package fr.dutra.tools.maven.deptree.core;

import java.io.BufferedWriter;
import java.io.IOException;

import org.apache.commons.io.output.StringBuilderWriter;



/**
 * Base class for visitors that generate an output that is identical to the output generated by the maven command:
 * <pre>mvn dependency:tree -DoutputType=text</pre>
 * @author Alexandre Dutra
 *
 */
public abstract class MavenDependencyTreeAbstractTextVisitor implements MavenDependencyTreeVisitor {


    private final StringBuilderWriter sbw;

    private final BufferedWriter bw;

    public MavenDependencyTreeAbstractTextVisitor() {
        sbw = new StringBuilderWriter();
        bw = new BufferedWriter(sbw);
    }

    public void visit(MavenDependencyTreeNode node){
        try {
            writeNode(node);
            for (MavenDependencyTreeNode child : node.getChildNodes()) {
                visit(child);
            }
        } catch (IOException e) {
        }
    }

    private void writeNode(MavenDependencyTreeNode node) throws IOException {
        //the tree symbols
        writeTreeSymbols(node);
        //the node itself
        bw.write(node.toArtifactCanonicalForm());
        bw.newLine();
    }

    private void writeTreeSymbols(MavenDependencyTreeNode node) throws IOException {
        if(node.getParent() != null) {
            writeParentTreeSymbols(node.getParent());
            bw.write(getTreeSymbols(node));
        }
    }

    private void writeParentTreeSymbols(MavenDependencyTreeNode node) throws IOException {
        if(node.getParent() != null) {
            writeParentTreeSymbols(node.getParent());
            bw.write(getParentTreeSymbols(node));
        }
    }

    public abstract String getTreeSymbols(MavenDependencyTreeNode node);

    public abstract String getParentTreeSymbols(MavenDependencyTreeNode node);

    @Override
    public String toString() {
        try {
            bw.flush();
            sbw.flush();
            return sbw.toString();
        } catch (IOException e) {
            return null;
        } finally {
            try {
                bw.close();
            } catch (IOException e) {
            }
            sbw.close();
        }
    }

}
